@ECHO OFF
ECHO Borrando Base de Datos...
CALL "C:\\Program Files\\MariaDB 10.3\\bin\\mysql.exe" -u root --password=admin -e "DROP DATABASE IF EXISTS company;"
ECHO Creando Base de Datos...
CALL "C:\\Program Files\\MariaDB 10.3\\bin\\mysql.exe" -u root --password=admin -e "CREATE DATABASE company;"
ECHO Cargando Base de Datos ...
"C:\\Program Files\\MariaDB 10.3\\bin\\mysql.exe" -u root --password=admin company < db_backup_company.sql
ECHO Presione cualquier tecla para terminar...
PAUSE >nul